/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Main program body
  ******************************************************************************
  * @attention
  *
  * Minimum application for processing input audio from MEMS microphone (MP45DT02)
  * and output result to headphones. IIR low-pass filter on a 5 second recording
  * stored in RAM.
  *
  * Files generated by STM CubeMX
  *
  * Reminders:
  * - Include necessary HAL driver files (I2S, I2C, SPI)
  * - Include BSP headers from STM folder to the include path
  * - Add required BSP source files (e.g. stm32f4_discovery.c)
  * - Don't forget peripheral interrupt handlers (DMAs)
  * - Add PDMFilter.a to linker
  ******************************************************************************
  */
#include "main.h"

#define BUFF_SIZE 	INTERNAL_BUFF_SIZE
#define SAMPLE_N 	40000

#define FREQ 		8000U
#define BIT_DEPTH	16
#define CHANNELS 	2
#define VOLUME		30

void SystemClock_Config(void);

uint16_t samples[SAMPLE_N];
uint16_t buff[BUFF_SIZE];

int irqCounter = 0;
int REC_COMPLETE = 0;

void IIR_Filter();
/**
  * @brief  The application entry point.
  * @retval int
  */

int main(void)
{
  HAL_Init();

  SystemClock_Config();

  BSP_LED_Init(LED3);	// Red (error)
  BSP_LED_Init(LED4);	// Green (complete)
  BSP_LED_Init(LED6);	// Blue (recording)

  BSP_AUDIO_IN_Init(FREQ, BIT_DEPTH, CHANNELS);
  BSP_AUDIO_IN_Record((uint16_t*)&buff[0], BUFF_SIZE);

  BSP_LED_On(LED6);

  while (1)
  {
	  if(REC_COMPLETE){
		  BSP_LED_Off(LED6);
		  break;
	  }
  }

  BSP_AUDIO_IN_Stop();

  IIR_Filter();

  BSP_AUDIO_OUT_Init(OUTPUT_DEVICE_HEADPHONE, VOLUME, FREQ);
  BSP_AUDIO_OUT_Play((uint16_t*)&samples[0], SAMPLE_N*2);

  BSP_LED_On(LED4);

  while (1) {}

}

// Coefficients calculating using:
// https://www.earlevel.com/main/2013/10/13/biquad-calculator-v2/
double a0 = 0.5093089476504493;
double a1 = 1.0186178953008986;
double a2 = 0.5093089476504493;
double b1 = 0.7612880361259173;
double b2 = 0.2759477544758799;

/**
  * @brief  Low-pass IIR filter
  * @retval void
  */
void IIR_Filter(){

	// Difference equation:
	//y[n] = a0*x[n] + a1*x[n-1] + a2*x[n-2] - b1*y[n-1] - b2*y[n-2]

	uint16_t xn1,xn2,yn1,yn2;
	xn1 = samples[1];
	xn2 = samples[0];
	yn1 = yn2 = 0;
	int outN = 0;

	for(int n = 2; n < SAMPLE_N; n++){
		yn1 = samples[n-1];
		yn2 = samples[n-2];
		outN = a0*samples[n] + a1*xn1 + a2*xn2
			   -b1*yn1 - b2*yn2;
		xn1 = samples[n];
		xn2 = samples[n-1];

		samples[n] = outN;
	}
}


void BSP_AUDIO_IN_TransferComplete_CallBack(){

	int offset = irqCounter*BUFF_SIZE;

	BSP_AUDIO_IN_PDMToPCM((uint16_t*)&buff[0], &(samples[offset]));

	irqCounter++;
	if(irqCounter >= SAMPLE_N/BUFF_SIZE) REC_COMPLETE = 1;
}

/**
 * GENERATED BY CUBEMX
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Configure the main internal regulator output voltage 
  */
  __HAL_RCC_PWR_CLK_ENABLE();
  __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);
  /** Initializes the CPU, AHB and APB busses clocks 
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_NONE;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }
  /** Initializes the CPU, AHB and APB busses clocks 
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_HSI;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_0) != HAL_OK)
  {
    Error_Handler();
  }
}



/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
	BSP_LED_On(LED3);
	while(1){}
}

#ifdef  USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{ 
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     tex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */

/************************ (C) COPYRIGHT STMicroelectronics *****END OF FILE****/
